#!/bin/sh
#
#   Lib find from func name
#
#   2000/10/23 by oga

LIST=`ls *.a *.so *.sl  2>/dev/null`
for i in $LIST
do
    echo "## $i"
    nm $i |grep $* > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        nm $i |grep $*
    fi
done
