#!/bin/sh
#
#    suffix change    e.g. .JPG => .jpg
#
#    2000/10/10 by oga
#

if [ "$2" = "" -o "$1" = "-h" ]; then
    echo "usage: sufchg <old_suffix> <new_suffix>"
fi

OLDSUF=$1
NEWSUF=$2

for i in `ls *.$1`
do
    NEWNM=`echo $i |sed "s@\.$OLDSUF@\.$NEWSUF@"`
    echo "mv $i => $NEWNM"
    mv $i $NEWNM
done
